[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build"]

[caches]
skip = true

[start]
cmd = "npm start"

[variables]
PORT = "8080"
CACHE_BUST = "20251214-v3"
